[package]
name = "playground-systems-webgl"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
playground-core-types = { path = "../../core/types" }
playground-core-rendering = { path = "../../core/rendering" }
playground-core-ecs = { path = "../../core/ecs" }
playground-core-server = { path = "../../core/server" }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
nalgebra = { workspace = true }
axum = { workspace = true }