//! Version information for ECS module
//!
//! This module contains version constants generated by build.rs
//! through content hashing of the view directory.

// Include the generated version constants from build.rs
include!(concat!(env!("OUT_DIR"), "/versions.rs"));
