[package]
name = "playground-systems-networking"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
playground-core-types = { path = "../../core/types" }
playground-core-ecs = { path = "../../core/ecs" }
playground-core-server = { path = "../../core/server" }  # For packet types and channel definitions
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }
futures-util = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
bincode = { workspace = true }
async-trait = { workspace = true }
tokio-tungstenite = "0.20"  # For native WebSocket client