[package]
name = "playground-rendering"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
playground-types = { path = "../../core/types" }
playground-ecs = { path = "../../core/ecs" }
bytes = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

# WebGL dependencies
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "console",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "WebGlProgram",
    "WebGlShader",
    "WebGlBuffer",
    "WebGlTexture",
    "WebGlFramebuffer",
    "WebGlRenderbuffer",
    "WebGlUniformLocation",
    "WebGlVertexArrayObject",
    "WebGlActiveInfo",
    "WebGlSampler",
    "WebGlSync",
    "WebGlQuery",
    "WebGlTransformFeedback",
] }
js-sys = "0.3"

[features]
webgl = []