[package]
name = "playground-core-rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bytes = "1.5"
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1.36", features = ["sync"] }

[features]
default = []
webgl = []
vulkan = []