[package]
name = "playground-ecs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"
bytes = "1.5"
dashmap = "6.0"
parking_lot = "0.12"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.10", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
playground-types = { path = "../types" }
futures = "0.3"

[dev-dependencies]
tokio-test = "0.4"