[package]
name = "playground-core-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies (contracts only need minimal deps)
async-trait = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"