[package]
name = "playground-core-ecs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"
bytes = "1.5"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.10", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
playground-core-types = { path = "../types" }
futures = "0.3"
once_cell = "1.19"

[dev-dependencies]
tokio-test = "0.4"